using System;

namespace Withat.SourceCode;

internal static class Attributes
{
    public const string SourceCode = @"
// <auto-generated/>
using System;
namespace Withat;
[AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct)]
public class ExtendedWithAttribute : Attribute {}

[AttributeUsage(AttributeTargets.Property)]
public class ExtendedWithIgnoreAttribute : Attribute {}
";
}

