using System;
using System.Collections.Generic;
using System.Linq;
using Withat.Models;

namespace Withat.SourceCode;

internal static class RecordWithExtensions
{
    internal static string Generate(RecordTypeModel type) => $@"
// <auto-generated/>
using System;
using System.Threading.Tasks;
using System.Collections.Generic;
namespace {type.RecordNamespaceName};
public static class {type.RecordTypeNameMinified}_WithExtensions
{{
    {GenerateAllPathMethods(type)}
}}
";

    private static string GenerateAllPathMethods(RecordTypeModel type)
    {
        var plannedPaths = WithPathPlanner.Plan(type).ToArray();

        ValidateNoDuplicatePlannedPaths(plannedPaths);

        var sb = new System.Text.StringBuilder();
        var emitter = new WithMethodEmitter();

        foreach (var plan in plannedPaths)
        {
            if (!plan.HasNullableRecordSegment)
            {
                emitter.EmitEightOverloads(sb, type, plan, $"With{plan.PathSuffix}", NullPropagationKind.None);
            }
            else
            {
                emitter.EmitEightOverloads(sb, type, plan, $"TryWith{plan.PathSuffix}", NullPropagationKind.Safe);
                emitter.EmitEightOverloads(sb, type, plan, $"With{plan.PathSuffix}_OrThrow", NullPropagationKind.Throw);
            }
        }

        return sb.ToString();
    }

    private static void ValidateNoDuplicatePlannedPaths(IReadOnlyList<PlannedPath> plannedPaths)
    {
        var seen = new HashSet<string>();
        foreach (var plan in plannedPaths)
        {
            if (!seen.Add(plan.PathSuffix))
                throw new InvalidOperationException($"Withat: duplicate planned path detected: {plan.PathSuffix}");
        }
    }
    

}
